Fixes and upgrades to CMake testing system (#239)
* Adds PARFLOW_TEST_FORCE_MPIEXEC

On some systems, it is necessary for any binary compiled with mpi to be executed with the appropriate ${mpiexec} command. Setting PARFLOW_TEST_FORCE_MPIEXEC forces sequential tests to be executed with the ${MPIEXEC} command with 1 rank.

* CMake test changes for running MPI tests when pre/post flags are needed.

+ Fixes MPIEXEC_PRE/POSTFLAGS passing in ParflowTest.cmake
+ Fixes MPIEXEC_PRE/POSTFLAGS use in RunAmpsTest.cmake
+ Mostly cosmetic changes to RunParallelTest.cmake and RunFileCompareTest.cmake to make them and RunAmpsTest.cmake all output simmilar.

* Fixed erroneous -D use in ParflowTest.cmake

error: "-D={MPIEXEC_PREFLAGS=${MPIEXEC_PREFLAGS}"
fix: -DMPIEXEC_PREFLAGS=${MPIEXEC_PREFLAGS}

* Fixes improper expansion of 'ranks' in RunAmpsTest.cmake

* fixed version and COMMAND_ECHO issues in Run*Test.cmake

+ Bumped minimum version in Run*Test.cmake from 3.4 to 3.14

* Corrected order of MPIEXEC_PRE/POSTFLAGS in RunAmpsTest

* Stringify correct command variable in RunAmpsTest.cmake

* Fixed join cmake bug in RunAmpsTest.cmake

Co-authored-by: Steven Smith <smith84@llnl.gov>